M48
; DRILL file {KiCad 7.0.6-1.fc38} date Mon 24 Jul 2023 16:31:09 EDT
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-07-24T16:31:09-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.6-1.fc38
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.800
%
G90
G05
T1
X138.545Y-51.42
X143.395Y-51.42
T2
X138.245Y-48.39
X143.695Y-48.39
T0
M30
